#!/bin/bash
set -xv 
destdir=/work/jeff/backend/system 
if [ ! -d ${destdir} ] 
then
    mkdir ${destdir}
    mkdir ${destdir}/postgresql-config 
fi    

cp -r -P /etc/ ${destdir}/
rm ${destdir}/etc/*shadow*
rm -rf ${destdir}/etc/selinux  
cp -r /opt/redmine-1.2/config ${destdir}/redmine-config 
cp -r /opt/redmine-1.2/files ${destdir}/redmine-files
cp /work/pgsql/data/pg_hba.conf /work/pgsql/data/pg_ident.conf  /work/pgsql/data/postgresql.conf  ${destdir}/postgresql-config 
yum list installed >${destdir}/yum-installed

chown -R jeff:jeff ${destdir} 
chmod -R u+rw ${destdir} 
