#!/bin/bash
#  dump postgresql using dump all
#  daily dumps go into /work/jeff/dumps/pgdump-Wed  (etc)
#    could use date, but that complicates the rest of this and we can get the date
#    from the file timestamp. 
#  every monday a dump goes into /work/jeff/dumps/weekly/week-number-of-year%8 
#    so there are at most 8 of those, redundant as there's also one every month  
#  the first of every month, one goes into /work/jeff/dumps/monthly 
#    so there will be one of these for every month 
set -xv 
localtarget=/work/jeff/dumps 
todays=${localtarget}/`date +pgdump+%a`
bzipped=${localtarget}/`date +pgdump+%a.bz2`
weekday=`date +%a`
pg_dumpall > $todays 
bzip2 $todays 

if [ `date +%w` == 1 ] 
then 
    # week number mod 8 
    wn=$((`date +%U` % 8))   
    wd=$localtarget/weekly/$wn 
    if [ ! -d $wd ] 
    then 
        mkdir $wd 
    fi 
    cp $bzipped $wd 
fi 

# first day of month? 
if [ `date +%d` -eq 1 ]
then
   month=`date +%m`
   mondir =  $localtarget/monthly/$month  
   if [ ! -d $mondir ] 
   then 
       mkdir $mondir 
   fi 
   cp $bzipped $mondir 
fi 


