#!/bin/bash
mv /work/jeff/logs/hotwire_api_analysis.log `date +/work/jeff/logs/hotwire_api_analysis-%m-%d.log`
python /work/jeff/backend/scrapers/hotwire_api/hotwire_api/spiders/hotwire_api_spider.py --do-all-cities --do-spider --result-count=20 --debug-level=0  --offsets=1,2,7

